
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Usuario
 */
public class ComprobacionNumerica extends javax.swing.JFrame {

    /**
     * Creates new form ComprobacionNumerica
     */
    public ComprobacionNumerica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblIngreseNum = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JTextField();
        btnComprobar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 153));
        jLabel1.setText("Comprobación Númerica");

        lblIngreseNum.setForeground(new java.awt.Color(0, 0, 0));
        lblIngreseNum.setText("Ingrese un número:");

        txtNum1.setBackground(new java.awt.Color(204, 255, 255));
        txtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum1ActionPerformed(evt);
            }
        });

        btnComprobar.setBackground(new java.awt.Color(102, 255, 102));
        btnComprobar.setForeground(new java.awt.Color(0, 0, 0));
        btnComprobar.setText("Comprobar");
        btnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblIngreseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnComprobar)
                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIngreseNum))
                .addGap(47, 47, 47)
                .addComponent(btnComprobar)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum1ActionPerformed

    private void btnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarActionPerformed
        // TODO add your handling code here:
        int Num1 = Integer.parseInt(txtNum1.getText());

        // Comprobar si el número es perfecto
        if (numero_Perfecto(Num1)) {
            JOptionPane.showMessageDialog(rootPane, "El número es perfecto.");
        } else {
            JOptionPane.showMessageDialog(rootPane, "El número no es perfecto.");
        }

        // Comprueba si el número es primo
        if (numero_Primo(Num1)) {
            JOptionPane.showMessageDialog(rootPane, "El número es primo.");

            // Mostrar la lista de números primos znteriores al ingresado
            nmrs_Primos_Anteriores(Num1);

            // Mostrar la sumatoria de números primos anteriores al ingresado
            int sumatoria = suma_Numeros_Primos(Num1);
            JOptionPane.showMessageDialog(rootPane, "Sumatoria de números primos menores al ingresado: " + sumatoria);

            // Calcula la raíz cuadrada de la sumatoria
            double raizCuadrada = Math.sqrt(sumatoria);
            JOptionPane.showMessageDialog(rootPane, "Raíz cuadrada de la sumatoria: " + raizCuadrada);
        } else {
            JOptionPane.showMessageDialog(rootPane, "El número no es primo.");
        }
    }//GEN-LAST:event_btnComprobarActionPerformed

    //MÉTODO PARA VER SI EL NÚMERO ES PERFECTO
    public static boolean numero_Perfecto(int numero) {
        int suma = 0;
        for (int i = 1; i < numero; i++) {
            if (numero % i == 0) {
                suma += i;
            }
        }
        return suma == numero;
    }
    
    //MÉTODO DE PARA VER SI ES PRIMO
    public static boolean numero_Primo(int numero) {
        if (numero <= 1) {
            return false;
        }
        for (int i = 2; i <= Math.sqrt(numero); i++) {
            if (numero % i == 0) {
                return false;
            }
        }
        return true;
    }
    
    // MÉTODO PARA OBTENER NÚMEROS PRIMOS ANTERIORES 
    public static void nmrs_Primos_Anteriores(int numero) {
        ArrayList<Integer> primos_Anteriores = new ArrayList<>();
        for (int i = 2; i < numero; i++) {
            if (numero_Primo(i)) {
                primos_Anteriores.add(i);
            }
        }
        if (primos_Anteriores.size() > 0) {
            JOptionPane.showMessageDialog(null, "Números primos anteriores a " + numero + ": " + primos_Anteriores.toString());
        } else {
            JOptionPane.showMessageDialog(null, "No hay números primos anteriores a " + numero);
        }
    }


    // MÉTODO PARA OBTENER LA SUMATORIA DE NÚMEROS PRIMOS ANTERIORES
    public static int suma_Numeros_Primos(int numero) {
        int suma = 0;
        for (int i = 2; i < numero; i++) {
            if (numero_Primo(i)) {
                suma += i;
            }
        }
        return suma;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprobacionNumerica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprobar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIngreseNum;
    private javax.swing.JTextField txtNum1;
    // End of variables declaration//GEN-END:variables
}
